server:
  port: ${port:0}
spring:
  application:
    name: UMS-ACTIONITEMS-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root

    url: jdbc:postgresql://localhost:5432/actionitem
    username: postgres
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
